// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeuXNYmQilYtxTWySq2NhowJKJWzxw_q8',
    appId: '1:631348234096:web:bee13dc036f57d47feb1b5',
    messagingSenderId: '631348234096',
    projectId: 'lebenshygiene-anwendung',
    authDomain: 'lebenshygiene-anwendung.firebaseapp.com',
    storageBucket: 'lebenshygiene-anwendung.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvoa0uqf0vk2HKHZsig1UHyOaYkzhBcs',
    appId: '1:631348234096:android:2c016be033a68875feb1b5',
    messagingSenderId: '631348234096',
    projectId: 'lebenshygiene-anwendung',
    storageBucket: 'lebenshygiene-anwendung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlnWmKpjs-BMO-2_GFkCyCHfS0MsI7IjY',
    appId: '1:631348234096:ios:95f4da7a8fd474a5feb1b5',
    messagingSenderId: '631348234096',
    projectId: 'lebenshygiene-anwendung',
    storageBucket: 'lebenshygiene-anwendung.firebasestorage.app',
    iosBundleId: 'com.example.lebenshygieneAnwendung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlnWmKpjs-BMO-2_GFkCyCHfS0MsI7IjY',
    appId: '1:631348234096:ios:95f4da7a8fd474a5feb1b5',
    messagingSenderId: '631348234096',
    projectId: 'lebenshygiene-anwendung',
    storageBucket: 'lebenshygiene-anwendung.firebasestorage.app',
    iosBundleId: 'com.example.lebenshygieneAnwendung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeuXNYmQilYtxTWySq2NhowJKJWzxw_q8',
    appId: '1:631348234096:web:ab32bfad3f472a51feb1b5',
    messagingSenderId: '631348234096',
    projectId: 'lebenshygiene-anwendung',
    authDomain: 'lebenshygiene-anwendung.firebaseapp.com',
    storageBucket: 'lebenshygiene-anwendung.firebasestorage.app',
  );
}
